[package]
name = "DeltaParq"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "58.2.0"
arrow-array = "58.2.0"
arrow-schema = "58.2.0"
futures = "0.3.32"
futures-core = "0.3.32"
libcorn = "0.10.1"
parquet = {version="58.2.0", features=["async"]}
serde = "1.0.228"
tokio = {version="1.52.2", features=["full"]}
